[package]
name = "hls_wasm"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
hls_m3u8 = "0.1"
mpeg2ts = "0.1"
mse_fmp4 = "0.1"
serde = "1"
serde_derive = "1"
serde_json = "1"
trackable = "0.2"
url = "1"
url_serde = "0.2"
